[WIP] Add support for 2.10
propensive/contextual pull request #2
Opened 2016-12-15 09:40 UTC by nrinaudo

This (mostly) adds support for 2.10. Only one compilation problem remains:

```scala
error] /contribs/contextual/core/src/main/scala/contextual/contextual.scala:51: macro implementation has incompatible shape:
[error]  required: (c: scala.reflect.macros.Context)(exprs: c.Expr[contextual.Interpolator.Embedded[Prefix.this.interpolator.Inputs,Prefix.this.interpolator.type]]*): c.Expr[Any]
[error]  found   : (c: contextual.compat.Context)(exprs: c.Tree*): c.Tree
[error] type mismatch for parameter exprs: c.Expr[contextual.Interpolator.Embedded[Prefix.this.interpolator.Inputs,Prefix.this.interpolator.type]]* does not conform to c.universe.Tree*
[error]       macro Macros.contextual[C, P]
```

I'm making a PR as is following our [gitter conversation](https://gitter.im/propensive/contextual?at=5851cfcafb22792b3b64e9c6).

2016-12-15 11:23 UTC, nrinaudo commented
[This](https://github.com/nrinaudo/contextual/blob/ddaa43c1ed05cd2f6dfb1befa599346bc4f5c690/core/src/main/scala/contextual/contextual.scala#L117)  still fails to compile - I don't know how to get a quasiquote to return anything but a `c.Tree`. Do I need to go through `reify`, or is there something clever to do there?

2016-12-16 11:14 UTC, propensive requested changes

2016-12-16 11:14 UTC, propensive commented on core/src/main/scala/contextual/contextual.scala
> +  def evaluator(contexts: Seq[Ctx], contextual: Contextual[StaticPart]): contextual.context.Expr[Any] = {
I think we should leave the return type as `context.Tree`. You'll need to implement a method, say, `compat.macroReturn`, which always returns `context.Tree`, but takes `context.Expr` in the Scala 2.10 implementation, and `context.Tree` in the 2.11+ version.

2016-12-16 11:14 UTC, propensive commented on core/src/main/scala/contextual/macros.scala
> +  (c: compat.Context)(exprs: c.Expr[Any]*): c.Expr[Any] = {
Let's leave the `exprs` type as `c.Tree`, and use a new method in `compat` to deal with it appropriately in the different Scala versions.

2016-12-16 11:14 UTC, propensive commented on core/src/main/scala/contextual/contextual.scala
> +    def expressions: Seq[context.Expr[Any]] = Nil
Leave this as `context.Tree`, and call `.map(compat.toTree)` on the expressions value where necessary. You'll need to implement `compat.toTree` to call `.tree` on an `c.Expr` in 2.10, or just be the identity in 2.11/2.12.

2016-12-16 16:13 UTC, nrinaudo commented on core/src/main/scala/contextual/contextual.scala
> +  def evaluator(contexts: Seq[Ctx], contextual: Contextual[StaticPart]): contextual.context.Expr[Any] = {
I must admit I've no idea how to turn a `c.Expr`  into a `c.Tree`, aside from using [macro-compat](https://github.com/milessabin/macro-compat)...

2016-12-17 17:26 UTC, nrinaudo commented
Not much point now that macro-compat is used.

2016-12-17 17:26 UTC, closed without merging